apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - policies/disallow-priv-escalation.yaml
  - policies/enforce-readonly-rootfs.yaml
  - policies/require-resource-limits.yaml
namespace: kyverno
